language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: j68XFfMfYZlH942XGvWRpuLctPxjgdMfs5khTCMawtmUcgYVVfMU8nYKSQ4YgC2PL8+31Pu5OupJ+M/DTkhziEs7sEFkI10hG8xMpnkQ2lZDTuzwEXeH0mpGI/gON34eQO7Imb7Wy8WnQ/jI0kicmnT7EwIXDKLUV7LJYRKy7Aq80ZMpil4qNbi4d2Z0FelgAAZfC8yAtZETBqiufBCKgJ378i/DO1+dpTM3vcOuAf6C1XnHnCHKMuJxs1+wQPP5rMtm1Ntw7P7V7RZTpl3mbCOQeJjt85sIKBewQVsjBAWIE6GszEDObVoSDgQemkgtOkZzFZJ91GMw6mbNVCJpxvDI6TprF0OTSWfKkqpuyn8cVoBCWefiXDWkq4R9CDjuGCPfuCtxLSh7Qb5DaWiCWyDwfnC07gQb0sHzAzCe1AW3Yj+oaLT26yTsM+ENn8sPBiCSRGzo6fEfqHjfhBj5Dq3eDhHAOY1bXtxP4x5uqszDrO1cZ9T/kHqboZxE9p51hIwHcvjb+v1AEqr0wXQZOkU9c2EoUd+6A0KLZAsXMIT9liNLB9LC4p9/uGPF1nHND5I4stcGAfFEqbHVpXAre4wqitIr0pHwja9D2gkG1Q6Ur0xwJSEPqnNSqMjfjXmzK3/6KY3k3/vSeX5SuBty4Z2hv790kRRh0by/iFmINbY=
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
